# Generated by Django 4.2.4 on 2023-08-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_landing_page', '0003_customuser_tipo_usuario'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
